'use client'

import type { DashboardData, EventOption } from '@/lib/dashboard'
import styles from './EODReport.module.css'

interface Props {
  data:    DashboardData
  filter:  string
  events:  EventOption[]
  onClose: () => void
}

export default function EODReport({ data, filter, events, onClose }: Props) {
  const eventName = filter === 'today'
    ? 'Today'
    : events.find(e => e.id === filter)?.name ?? 'Event'

  const date = new Date().toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric',
  })

  const handlePrint = () => window.print()

  const handleCopy = () => {
    navigator.clipboard.writeText(buildPlainText(data, eventName, date))
  }

  return (
    <div className={styles.overlay} onClick={onClose}>
      <div className={styles.modal} onClick={e => e.stopPropagation()}>
        <div className={styles.header}>
          <div>
            <div className={styles.title}>End-of-day report</div>
            <div className={styles.subtitle}>{eventName} · {date}</div>
          </div>
          <div className={styles.headerActions}>
            <button className={styles.actionBtn} onClick={handleCopy}>Copy</button>
            <button className={styles.actionBtn} onClick={handlePrint}>Print</button>
            <button className={styles.closeBtn} onClick={onClose}>✕</button>
          </div>
        </div>

        <div className={styles.body} id="eod-print">
          {/* Summary */}
          <section className={styles.section}>
            <div className={styles.sectionTitle}>Summary</div>
            <div className={styles.grid2}>
              <Stat label="Total revenue"   value={`₹${data.revenue.toLocaleString('en-IN')}`} />
              <Stat label="Total orders"    value={String(data.orderCount)} />
              <Stat label="Avg order value" value={`₹${data.avgOrderValue}`} />
              <Stat label="Combo attach"    value={`${data.comboAttachRate}%`} />
              {data.avgServeTime !== null && (
                <Stat label="Avg serve time" value={`${data.avgServeTime} min`} />
              )}
              <Stat label="Est. waste cost" value={`₹${data.estWasteCost}`} highlight={data.estWasteCost > 500} />
            </div>
          </section>

          {/* Item performance */}
          <section className={styles.section}>
            <div className={styles.sectionTitle}>Item performance</div>
            <table className={styles.table}>
              <thead>
                <tr>
                  <th>Item</th>
                  <th>Qty sold</th>
                  <th>Revenue</th>
                </tr>
              </thead>
              <tbody>
                {data.itemSales.map(item => (
                  <tr key={item.name}>
                    <td>{item.name}</td>
                    <td>{item.qty}</td>
                    <td>₹{item.revenue.toLocaleString('en-IN')}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>

          {/* Payment breakdown */}
          <section className={styles.section}>
            <div className={styles.sectionTitle}>Payment breakdown</div>
            <div className={styles.grid3}>
              <Stat label="UPI"  value={`${data.paymentSplit.upi}%`} />
              <Stat label="Cash" value={`${data.paymentSplit.cash}%`} />
              <Stat label="Card" value={`${data.paymentSplit.card}%`} />
            </div>
          </section>

          {/* Peak hour */}
          {data.hourlySales.length > 0 && (
            <section className={styles.section}>
              <div className={styles.sectionTitle}>Peak hour</div>
              {(() => {
                const peak = data.hourlySales.reduce((a, b) => b.revenue > a.revenue ? b : a)
                const h = peak.hour
                const label = h === 0 ? '12 AM' : h < 12 ? `${h} AM` : h === 12 ? '12 PM' : `${h - 12} PM`
                return (
                  <Stat label={label} value={`₹${peak.revenue.toLocaleString('en-IN')}`} />
                )
              })()}
            </section>
          )}

          <div className={styles.footer}>
            Generated by Munchies & Co. POS · {date}
          </div>
        </div>
      </div>
    </div>
  )
}

function Stat({ label, value, highlight }: { label: string; value: string; highlight?: boolean }) {
  return (
    <div className={styles.stat}>
      <div className={styles.statLabel}>{label}</div>
      <div className={`${styles.statValue} ${highlight ? styles.statHighlight : ''}`}>{value}</div>
    </div>
  )
}

function buildPlainText(data: DashboardData, eventName: string, date: string): string {
  const lines = [
    `MUNCHIES & CO. — END OF DAY REPORT`,
    `${eventName} · ${date}`,
    ``,
    `SUMMARY`,
    `Revenue:        ₹${data.revenue.toLocaleString('en-IN')}`,
    `Orders:         ${data.orderCount}`,
    `Avg order:      ₹${data.avgOrderValue}`,
    `Combo attach:   ${data.comboAttachRate}%`,
    data.avgServeTime !== null ? `Avg serve time: ${data.avgServeTime} min` : null,
    `Est. waste:     ₹${data.estWasteCost}`,
    ``,
    `ITEM PERFORMANCE`,
    ...data.itemSales.map(i => `${i.name.padEnd(20)} ${String(i.qty).padStart(3)} sold   ₹${i.revenue}`),
    ``,
    `PAYMENT SPLIT`,
    `UPI: ${data.paymentSplit.upi}%   Cash: ${data.paymentSplit.cash}%   Card: ${data.paymentSplit.card}%`,
  ]
  return lines.filter(l => l !== null).join('\n')
}